### ISSUE TITLE
How to get this working on a raspberry pi

### ISSUE THREAD

**Issue by Chief-T1** [georgegebbett/recipe-buddy#403]
Hi,

I've been trying to get this working on a raspberry pi. I've had numerous issues. 
The first was related to the alpine linux version not working, related to this issue: https://github.com/nodejs/docker-node/issues/1589.

I fixed this by changing the Dockerfiles build line to this: `FROM node:18-alpine`

I've now got issues with MongoDB not connecting and I am getting the following errors: 
```
WARNING: MongoDB 5.0+ requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
  see https://jira.mongodb.org/browse/SERVER-55178
  see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
/usr/local/bin/docker-entrypoint.sh: line 414:    28 Illegal instruction     "${mongodHackedArgs[@]}" --fork
```
I've read online that I need to use an older version of MongoDB and so have changed the image in my docker compose file to use `mongo:4.4`. I'm still getting errors, can you please advise what else I need to change to get this to work? 

The docker compose file I'm using is below: 
```
version: "3.4"

services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db

  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /api
    depends_on:
      - "mongo"


  frontend:
    build:
      context: ./app
    depends_on:
      - "backend"


volumes:
  mongo_db:
```

Thank you
