### ISSUE TITLE
Unable to connect to Grocy

### ISSUE THREAD

**Issue by Bush-cat** [georgegebbett/recipe-buddy#492]
I wanted to try out the Application, wanted to add a Recipe but I couldn't choose any Products, in the Settings I saw the message "Not connected to Grocy, Unable to connect to Grocy - check your URL and API key"
In Grocy at the API Keys, it says Last used is Never for my recipe-buddy api key
I can ping my Server from the container and added other Applications like Grocy Android with a differrent API Key before.
I tried a new API key and tried my nginx proxy manager domain and ip+port.

Here is my docker compose which I run in Portainer
```yml
services:
    recipe-buddy:
        ports:
            - 3005:3000
        volumes:
            - /volume1/smarthome/configs/recipe-buddy/config:/home/node/app/data
        environment:
            - GROCY_API_KEY=REDACTED
            # - GROCY_BASE_URL="https://grocy.REDACTED"
            - GROCY_BASE_URL="http://192.168.111.100:9192"
            - NEXTAUTH_SECRET=REDACTED
            - NEXTAUTH_URL=https://recipe.REDACTED
        image: ghcr.io/georgegebbett/recipe-buddy
```

**Comment by georgegebbett** [comment]
That's odd - are you saying that you are able to ping the Grocy server from within the Recipe Buddy container? If so I can't think of a reason you wouldn't be able to connect from one to the other... What version of Grocy are you running?

**Comment by Bush-cat** [comment]
Correct, with the sh shell in the recive buddy container, I can ping the grocy IP and port.

I installed grocy as a homeassistant addon a week ago, apparrently it's running Version 4.0.3, there seems to be a newer Version available 4.2.0.
I will try setting grocy up again outside homeassistant

**Comment by Bush-cat** [comment]
I tried again, completely new containers, latest recipe-buddy and latest grocy 4.2.0, I tried many methods to connect the containers, network mode, host mode, all that stuff but still no success.

It would be great to have more details on on where it fails in the logs

**Comment by lionelripoll** [comment]
I think I have the same issue.
I can't connect to the server:
<img width="863" alt="image" src="https://github.com/georgegebbett/recipe-buddy/assets/19290920/9a593d88-8256-4655-ba12-eb8c88eb0f59">

Grocy is running in home assistant. I can ping home assistant in the contener
`ping homeassistant.local`
or 
`ping homeassistant.local:8123`

this is the command I used: 
`docker run \
 -p 3005:3000 \
 -v rb_data:/home/node/app/data \
 --env GROCY_API_KEY=AgplxUgwoqxnLPqDUXdotDOLcvCNg7nQZ1Zv5kEp6x1CAL0u** \
 --env GROCY_BASE_URL=http://homeassistant.local:8123 \
 --env NEXTAUTH_SECRET=7LO8hR4dl3+V8L7UawOkfv19qMA6MEzl5O9XIHAHN3** \
 --env NEXTAUTH_URL=http://localhost:3005 \
 ghcr.io/georgegebbett/recipe-buddy`

I also tried to add the subdirectory:
`docker run \
 -p 3005:3000 \
 -v rb_data:/home/node/app/data \
 --env GROCY_API_KEY=AgplxUgwoqxnLPqDUXdotDOLcvCNg7nQZ1Zv5kEp6x1CAL0u** \
 --env GROCY_BASE_URL=http://homeassistant.local:8123/a0d7b954_grocy/ \
 --env NEXTAUTH_SECRET=7LO8hR4dl3+V8L7UawOkfv19qMA6MEzl5O9XIHAHN3** \
 --env NEXTAUTH_URL=http://localhost:3005 \
 ghcr.io/georgegebbett/recipe-buddy`

**Comment by Bush-cat** [comment]
@lionelripoll port 8123 only runs the homeassistant webui, it has nothing to do with grocy, there was an option to open a port or network for the grocy addon configuration, use that and then you can use the grocy api with the port you set there.

**Comment by Bush-cat** [comment]
I was hoping to be able to use grocy with this project but making items manually in grocy is too annoying for me so I will have to uninstall grocy, I'm willing to try it again sometime if the Software works

**Comment by valerian-guichard** [comment]
Hi ! i have the same problem : here is my docker compose file :
`  recipe-buddy:
      ports:
          - 3005:3000
      volumes:
          - /opt/recipe-buddy/data:/home/node/app/data
      environment:
          - GROCY_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          - GROCY_BASE_URL=http://192.168.0.5:9283/
          - NEXTAUTH_SECRET=YPiVZW1WXFy55WLDUXuwnieyg9J5j3gZl0A4fodAh6M
          - NEXTAUTH_URL=http://192.168.0.5:3005/
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Paris
      image: ghcr.io/georgegebbett/recipe-buddy`

I get the same "Not connected to grocy" message and can't find out why nor how to solve it,
I would really appreciate help :))

**Comment by sidial01** [comment]
I was having a similar issue, except I wasn't even getting an error on the settings page. I had get into the docker console to ping items. However, what I found MOST useful in troubleshooting was getting into Grocy's API browser, and using the API key assigned for Recipe Buddy. That allowed me to determine that the API was not being accessed by Recipe Buddy at all. 

Since I have Grocy running in a Grocy-specific network configuration in Docker (to let it work properly with BarcodeBuddy), RecipeBuddy needs to 
1) be on the same network in Docker, 
2) reference the INTERNAL IP AND PORT. For me, that was 172.20.0.x:80. (It is NOT the 9283 default published port for Grocy-Docker.) I also changed the "nextauth_url" to the RecipeBuddy container's manually-configured internal docker IP vs the host IP. 

The cURL command won't work directly in the Docker command line without some adjustments, but this is the cURL that finally worked:

curl -X 'GET' \
  'http://grocy_internal_container_ip:80/api/system/info' \
  -H 'accept: application/json' \
  -H 'GROCY-API-KEY: 	$api_key'

So for "GROCY_BASE_URL", the correct setting was "grocy_internal_container_ip:80", rather than "docker_host_ip:9283". 

Steps for resolution: 

1. Connect to Docker console for Recipe Buddy container (using SH). 
2. Install cURL. Alpine command: apk --no-cache add curl  (https://www.shellhacks.com/alpine-install-curl/)
3. Attempt the Grocy API commands generated from the internal REST browser. Time outs occurred with no response.
4. Pings to the IP (same host) were just fine. 
5. Install telnet (https://devcoops.com/install-telnet-on-alpine-linux/ ). 
6. telnet host_ip 9283 -- failed, time out. 
7. telnet grocy_docker_ip 9283 -- failed, connection refused.
8. Attempted the cURL command again, changing to grocy_docker_ip:80 in the REST API browser generated code. Response! 
9. Made those changes to the ENV from Portainer's interface, and redeployed the container. Success!

**Comment by Kimbaras** [comment]
I'm having a similar issue using Grocy 4.2.0 and latest RecipeBuddy image.

I'm getting the "Not connected" error in the setting tab
![Immagine 2024-10-24 123050](https://github.com/user-attachments/assets/f27670d5-2510-4967-b900-7904606374bf)

I've quickly tried @sidial01 solution / workaround but I wasn't able to get it to work, will try a little bit more focused later.

**Comment by Stretsh** [comment]
Installed Grocy using the default instructions (but with Portainer), and it was added in a separate network in Grocy. Same goes for RB. So I think it is important that the owner adds this for clarity in the doc/readme.

> 1. be on the **same network in Docker**,
> 2. reference the **INTERNAL IP AND PORT**. For me, that was 172.20.0.x:80. (It is **NOT the 9283 default published port** for Grocy-Docker.) I also changed the "nextauth_url" to the RecipeBuddy container's manually-configured internal docker IP vs the host IP.
> 
> So for "GROCY_BASE_URL", the correct setting was "grocy_internal_container_ip:80", rather than "docker_host_ip:9283".

This is important to know. Helped me.

**Comment by jayjar291** [comment]
I am also unable to connect:

This is the SH output running the curl commands
```
/home/node/app # curl -X 'GET' 'grocy:80/api/system/info' -H 'accept: application/json' -H 'GROCY-API-KEY:[[[REDACTED]]]'
{"grocy_version":{"Version":"4.6.0","ReleaseDate":"2026-03-06"},"php_version":"8.5.3","sqlite_version":"3.51.2","db_version":255,"os":"Linux 6.1.0-41-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.158-1 (2025-11-09) x86_64","client":"curl\/8.14.1"}/home/node/app # 
/home/node/app # 
/home/node/app # 
/home/node/app # curl -X 'GET' 'grocy.alpha.jtek:80/api/system/info' -H 'accept: application/json' -H 'GROCY-API-KEY:[[[REDACTED]]]'
curl: (7) Failed to connect to grocy.alpha.jtek port 80 after 1 ms: Could not connect to server
/home/node/app # curl -X 'GET' 'grocy.alpha.jtek:9283/api/system/info' -H 'accept: application/json' -H 'GROCY-API-KEY:[[[REDACTED]]]'
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
/home/node/app # curl -X 'GET' 'https://grocy.alpha.jtek:9283/api/system/info' -H 'accept: application/json' -H 'GROCY-API-KEY:5XdMr9WdkXk55lu2VpGFA5YvtzYrSckhT1K7OhH1F4WfXSQc
wN'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.
/home/node/app #
```

And here is my docker config for both grocy and recipe buddy

```
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/grocy/config:/config
    ports:
      - 9283:443
    restart: unless-stopped
  recipe-buddy:
    ports:
      - 3005:3000
    volumes:
      - /path/to/grocy/config/rb_data:/home/node/app/data
    environment:
      - GROCY_API_KEY=[[[REDACTED]]]
      - GROCY_BASE_URL=grocy:80
      - NEXTAUTH_SECRET=[[[REDACTED]]]
      - NEXTAUTH_URL=http://rbuddy.alpha.jtek:3005
    image: ghcr.io/georgegebbett/recipe-buddy
```

I am running my own local DNS and CA for local HTTPS.
