### ISSUE TITLE
Blank Product/Unit

### ISSUE THREAD

**Issue by Servinjesus1** [georgegebbett/recipe-buddy#500]
Does recipe import pull "Grocy stock" from actual Stock or Products tables? I suspect it should pull from the Product table - not what's actually in stock right now. That said, mine is pulling from neither.

I'm getting reasonable log messages stating that the instance is set up.

Simple recipe appears to scrape fine:

```
{"level":30,"time":1725658727704,"pid":31,"hostname":"1b710d5b2dd3","recipe":{"name":"Easy Hummus (Better than Store-Bought)","url":"https://www.inspiredtaste.net/15938/easy-and-smooth-hummus-recipe/","steps":"In the bowl of a food processor, combine the tahini and lemon juice and process for 1 minute. Scrape the sides and bottom of the bowl, then process for 30 seconds more. This extra time helps &#8220;whip&#8221; or &#8220;cream&#8221; the tahini, making the hummus smooth and creamy.\nAdd the olive oil, minced garlic, cumin, and a 1/2 teaspoon of salt to the whipped tahini and lemon juice. Process for 30 seconds, scrape the sides and bottom of the bowl, and then process for another 30 seconds or until well blended.\nAdd half of the chickpeas to the food processor and process for 1 minute. Scrape the sides and bottom of the bowl, then add the remaining chickpeas and process them until thick and relatively smooth, 1 to 2 minutes.\nThe hummus will likely be too thick and still have tiny bits of chickpea. To fix this, slowly add 2 to 3 tablespoons of cold water or aquafaba with the food processor turned on until you reach the perfect consistency.\nTaste and adjust as needed. Serve hummus with a drizzle of olive oil and a sprinkle of paprika, sumac, or Za&#8217;atar.\nStore homemade hummus in an airtight container and refrigerate for up to one week. Freeze, covered with a thin layer of olive oil, for up to one month.","imageUrl":"https://www.inspiredtaste.net/wp-content/uploads/2019/07/The-Best-Homemade-Hummus-Recipe-1200.jpg","servings":6},"ingredients":[{"scrapedName":"1 (15oz) can chickpeas or 1 ½ cups (250g) cooked chickpeas"},{"scrapedName":"1/4 cup (60ml) fresh lemon juice, 1 large lemon"},{"scrapedName":"1/4 cup (60ml) well-stirred tahini, try our homemade tahini recipe"},{"scrapedName":"1 small garlic clove, minced"},{"scrapedName":"2 tablespoons (30ml) extra-virgin olive oil, plus more for serving"},{"scrapedName":"1/2 teaspoon ground cumin"},{"scrapedName":"Salt to taste"},{"scrapedName":"2 to 3 tablespoons (45ml) cold water or aquafaba"},{"scrapedName":"Dash ground paprika, sumac, or Za&#8217;atar for serving"}],"msg":"Recipe added"}
```

but during import nothing is shown to select for product/unit.

---

Grocy: `lscr.io/linuxserver/grocy:latest` `61522391c2212c794fc8336294d6d3227fb0d7febb3eb7b597466f6931080a44`
Recipe-Buddy: `ghcr.io/georgegebbett/recipe-buddy:latest` `8b9455aeb39a111c972d424be6791804ce08bd011275e04f405d30a2652910ab`

Compose:
```
---
services:
  recipe-buddy:
    image: ghcr.io/georgegebbett/recipe-buddy
    container_name: grocy-recipe-buddy
    environment:
      - GROCY_API_KEY=${GROCY_API_KEY}
      - GROCY_BASE_URL=${GROCY_BASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3005
    ports:
      - 3005:3000
    volumes:
      - rb_data:/home/node/app/data

volumes:
  rb_data:
```
